name: "Build and populate cache"
on:
  workflow_dispatch:
  # To be able to trigger a rebuild manually by (un)assigning someone
  # https://docs.github.com/en/actions/reference/workflows-and-actions/events-that-trigger-workflows#pull_request
  pull_request:
    types: [opened, reopened, synchronize, assigned, unassigned]
  push:
    branches:
      - main
      - master
  schedule:
    - cron:  '55 6 * * *'
jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        nixPath:
          - nixpkgs=channel:nixos-unstable
          - nixpkgs=channel:nixos-25.05
        runsOn:
          - ubuntu-latest
          - ubuntu-24.04-arm
    runs-on: "${{ matrix.runsOn }}"
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
    - name: Install nix
      uses: cachix/install-nix-action@v31
      with:
        nix_path: "${{ matrix.nixPath }}"
        extra_nix_config: |
          experimental-features = nix-command flakes
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - name: Show nixpkgs version
      run: nix-instantiate --eval -E '(import <nixpkgs> {}).lib.version'
    - name: Setup cachix
      uses: cachix/cachix-action@v16
      with:
        name: b10c-nixpkgs
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Check evaluation
      run: |
        nix-env -f . -qa \* --meta --xml \
          --allowed-uris https://static.rust-lang.org \
          --option restrict-eval true \
          --option allow-import-from-derivation true \
          --drv-path --show-trace \
          -I nixpkgs=$(nix-instantiate --find-file nixpkgs) \
          -I $PWD
    # run integration tests before we run the build since we need to build
    # the package anyway for the integration tests. So a build failure is
    # detected anyway.
    - name: Run NixOS module integration tests
      # We can't run the module integration tests on ARM due to the runners not having kvm enabled
      # error: a 'aarch64-linux' with features {kvm, nixos-test} is required to build '/nix/store/hk46b962dbx*-vm-test-run-*.drv', but I am a 'aarch64-linux' with features {benchmark, big-parallel, nixos-test, uid-range}
      if: matrix.runsOn == 'ubuntu-latest'
      run: nix flake check --print-build-logs --max-jobs 1
    - name: Build nix packages
      run: nix-build --max-jobs 1
